market_fees:
  steam:
    buyer_included: true
    seller_fee_rate: 0.15
    usd_cap: 2000
  skinport:
    buyer_extra_rate: 0.02
    seller_fee_rate: 0.12
  skinbaron:
    buyer_extra_rate: 0.00
    seller_fee_rate: 0.10
